apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    app: url_shortner_front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url_shortner_front
  template:
    metadata:
      labels:
        app: url_shortner_front
    spec:
      containers:
      - name: front
        image: mbhmma/url-shortly-front:v1.0.1-fr
        env:
          - name: NEXT_PUBLIC_COMPLET_BACK_URL
            valueFrom:
              secretKeyRef:
                name: server-url
                key: server-url
        ports:
        - containerPort: 3000