apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment
  labels:
    app: url_shortner_back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: url_shortner_back
  template:
    metadata:
      labels:
        app: url_shortner_back
    spec:
      containers:
      - name: back
        image: mbhmma/url-shortly-back:v1.0.0-bk
        env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-uri
                  key: mongo-uri
        ports:
        - containerPort: 4000