apiVersion: v1
kind: Service
metadata:
  name: frontu
  labels:
    app: url_shortner_front
spec:
  selector:
    app: url_shortner_front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000