apiVersion: v1
kind: Service
metadata:
  name: frontu
spec:
  selector:
    app.kubernetes.io/name: url_shortner_front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backu
spec:
  selector:
    app.kubernetes.io/name: url_shortner_front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
